default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    database: confectionery_shop_development
    username: vboxuser
    password:

test:
    <<: *default
    database: confectionery_shop_test

production:
    <<: *default
    database: confectionery_shop_production
    username: confectionery_shop
    password: <%= ENV["CONFECTIONERY_SHOP_DATABASE_PASSWORD"] %>
